blink_threshold_pitch: 0.7
blink_threshold_wo_pitch: 0.5
delay_drowsy_threshold: 2
frame_height: 720
frame_rate: 10
frame_width: 1280
min_face_detection_confidence: 0.5
min_face_presence_confidence: 0.7
model_path: ./models/face_landmarker_v2_with_blendshapes.task
num_faces: 1
perclos_threshold: 0.25
perclos_window_size: 60
pitch_threshold_negative: -40
pitch_threshold_positive: 40
